# Generated by Django 5.1.4 on 2025-01-04 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_book_liked_by'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
